language: java

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

os:
  - linux

dist: trusty

jdk:
  - oraclejdk8

install: true

script: mvn test compile -B -Dmaven.javadoc.skip=true
